$onText
Generated by nlp2mcp

This file contains the KKT (Karush-Kuhn-Tucker) conditions
for the original NLP model, transformed into MCP format.

KKT System Components:
  - Stationarity: ∇f + J^T λ + J^T ν - π^L + π^U = 0
  - Complementarity: g(x) ⊥ λ, h(x) = 0, bounds ⊥ π
  - Dual feasibility: λ, π^L, π^U ≥ 0
  - Primal feasibility: g(x) ≤ 0, h(x) = 0, lo ≤ x ≤ up
$offText

* ============================================
* Original Model Declarations
* ============================================

Sets
    c /H, H2, H2O, N, N2, NH, NO, O, O2, OH/
    i /H, N, O/
;

Parameters
    a(i,c) /H.H 1.0, H.H2 2.0, H.H2O 2.0, H.NH 1.0, H.OH 1.0, N.N 1.0, N.N2 2.0, N.NH 1.0, N.NO 1.0, O.H2O 1.0, O.NO 1.0, O.O 1.0, O.O2 2.0, O.OH 1.0, N.H 0.0, N.H2 0.0, N.H2O 0.0, N.O 0.0, N.O2 0.0, N.OH 0.0, H.N 0.0, H.N2 0.0, H.NO 0.0, H.O 0.0, H.O2 0.0, O.H 0.0, O.H2 0.0, O.N 0.0, O.N2 0.0, O.NH 0.0/
    mix(i) /h 2.0, n 1.0, o 1.0/
    gibbs(c) /H -10.021, H2 -21.096, H2O -37.986, N -9.846, N2 -28.653, NH -18.918, NO -28.032, O -14.64, o2 -30.594, OH -26.11/
    gplus(c)
;

* ============================================
* Variables (Primal + Multipliers)
* ============================================

* Primal variables: Original decision variables from the NLP
* Multipliers:
*   ν (nu_*): Free multipliers for equality constraints
*   λ (lam_*): Positive multipliers for inequality constraints
*   π^L (piL_*): Positive multipliers for lower bounds
*   π^U (piU_*): Positive multipliers for upper bounds

Variables
    energy
    nu_cdef(i)
    nu_xdef
;

Positive Variables
    x(c)
    xb
    piL_x(c)
    piL_xb
;

* ============================================
* Equations
* ============================================

* Stationarity: One equation per primal variable (except objvar)
* Complementarity: Equations for inequalities and bounds
* Equality constraints: Original equality constraints

Equations
    stat_x(c)
    stat_xb
    comp_lo_x_H
    comp_lo_x_H2
    comp_lo_x_H2O
    comp_lo_x_N
    comp_lo_x_N2
    comp_lo_x_NH
    comp_lo_x_NO
    comp_lo_x_O
    comp_lo_x_O2
    comp_lo_x_OH
    comp_lo_xb
    cdef(i)
    edef
    xdef
;

* ============================================
* Equation Definitions
* ============================================

* Stationarity equations
stat_x(c).. gplus(c) + log(x(c) / xb) + x(c) * 1 / (x(c) / xb) * 1 / xb ** 1 + sum(i, a(c,c) * nu_cdef(i)) + (-1) * nu_xdef - piL_x(c) =E= 0;
stat_xb.. sum(c, x(c) * 1 / (x(c) / xb) * ((-1) * x(c)) / xb ** 2) + sum(c, 0) * nu_cdef("H") + sum(c, 0) * nu_cdef("N") + sum(c, 0) * nu_cdef("O") + (1 - sum(c, 0)) * nu_xdef - piL_xb =E= 0;

* Lower bound complementarity equations
comp_lo_x_H.. x("H") - 0.001 =G= 0;
comp_lo_x_H2.. x("H2") - 0.001 =G= 0;
comp_lo_x_H2O.. x("H2O") - 0.001 =G= 0;
comp_lo_x_N.. x("N") - 0.001 =G= 0;
comp_lo_x_N2.. x("N2") - 0.001 =G= 0;
comp_lo_x_NH.. x("NH") - 0.001 =G= 0;
comp_lo_x_NO.. x("NO") - 0.001 =G= 0;
comp_lo_x_O.. x("O") - 0.001 =G= 0;
comp_lo_x_O2.. x("O2") - 0.001 =G= 0;
comp_lo_x_OH.. x("OH") - 0.001 =G= 0;
comp_lo_xb.. xb - 0.01 =G= 0;

* Original equality equations
cdef(i).. sum(c, a(i,c) * x(c)) =E= mix(i);
xdef.. xb =E= sum(c, x(c));
edef.. energy =E= sum(c, x(c) * (gplus(c) + log(x(c) / xb)));


* ============================================
* Model MCP Declaration
* ============================================

* Each line pairs an equation with a variable:
*   equation.variable
*
* This defines the complementarity problem:
*   equation ⊥ variable
*
* Meaning: equation = 0 if variable > 0
*          equation ≥ 0 if variable = 0

Model mcp_model /
    stat_x.x,
    stat_xb.xb,
    cdef.nu_cdef,
    edef.energy,
    xdef.nu_xdef,
    comp_lo_x_H.piL_x("H"),
    comp_lo_x_H2.piL_x("H2"),
    comp_lo_x_H2O.piL_x("H2O"),
    comp_lo_x_N.piL_x("N"),
    comp_lo_x_N2.piL_x("N2"),
    comp_lo_x_NH.piL_x("NH"),
    comp_lo_x_NO.piL_x("NO"),
    comp_lo_x_O.piL_x("O"),
    comp_lo_x_O2.piL_x("O2"),
    comp_lo_x_OH.piL_x("OH"),
    comp_lo_xb.piL_xb
/;

* ============================================
* Solve Statement
* ============================================

Solve mcp_model using MCP;