$onText
Generated by nlp2mcp

This file contains the KKT (Karush-Kuhn-Tucker) conditions
for the original NLP model, transformed into MCP format.

KKT System Components:
  - Stationarity: ∇f + J^T λ + J^T ν - π^L + π^U = 0
  - Complementarity: g(x) ⊥ λ, h(x) = 0, bounds ⊥ π
  - Dual feasibility: λ, π^L, π^U ≥ 0
  - Primal feasibility: g(x) ≤ 0, h(x) = 0, lo ≤ x ≤ up
$offText

* ============================================
* Original Model Declarations
* ============================================

Sets
    i /i1, i2, i3, i4, i5/
;

Alias(i, j);

Sets
    ij(i,j)
;

$onImplicitAssign
ij(i,j) = yes$(ord(i) < ord(j));
$offImplicitAssign

* ============================================
* Variables (Primal + Multipliers)
* ============================================

* Primal variables: Original decision variables from the NLP
* Multipliers:
*   ν (nu_*): Free multipliers for equality constraints
*   λ (lam_*): Positive multipliers for inequality constraints
*   π^L (piL_*): Positive multipliers for lower bounds
*   π^U (piU_*): Positive multipliers for upper bounds

Variables
    r
    x(i)
    y(i)
;

Positive Variables
    lam_circumscribe(i)
    lam_nooverlap(i,j)
    piL_r
    piL_x(i)
    piL_y(i)
    piU_r
    piU_x(i)
    piU_y(i)
;

* ============================================
* NLP Pre-Solve (warm-start for MCP duals)
* ============================================

$onMultiR
$include "data/gamslib/raw/cpack.gms"
$offMulti

* Transfer NLP duals to MCP multiplier initialization
lam_circumscribe.l(i) = abs(circumscribe.m(i));
lam_nooverlap.l(i,j) = abs(nooverlap.m(i,j));

* Transfer variable marginals to bound multipliers
piL_r.l$(abs(r.l - r.lo) < 1e-6) = abs(r.m);
piL_x.l(i)$(abs(x.l(i) - x.lo(i)) < 1e-6) = abs(x.m(i));
piL_y.l(i)$(abs(y.l(i) - y.lo(i)) < 1e-6) = abs(y.m(i));
piU_r.l$(abs(r.l - r.up) < 1e-6) = abs(r.m);
piU_x.l(i)$(abs(x.l(i) - x.up(i)) < 1e-6) = abs(x.m(i));
piU_y.l(i)$(abs(y.l(i) - y.up(i)) < 1e-6) = abs(y.m(i));

* Reset any NA/UNDF warm-start multiplier levels to 0 (#1322)
lam_circumscribe.l(i)$(NOT (lam_circumscribe.l(i) > -inf and lam_circumscribe.l(i) < inf)) = 0;
lam_nooverlap.l(i,j)$(NOT (lam_nooverlap.l(i,j) > -inf and lam_nooverlap.l(i,j) < inf)) = 0;
piL_r.l$(NOT (piL_r.l > -inf and piL_r.l < inf)) = 0;
piL_x.l(i)$(NOT (piL_x.l(i) > -inf and piL_x.l(i) < inf)) = 0;
piL_y.l(i)$(NOT (piL_y.l(i) > -inf and piL_y.l(i) < inf)) = 0;
piU_r.l$(NOT (piU_r.l > -inf and piU_r.l < inf)) = 0;
piU_x.l(i)$(NOT (piU_x.l(i) > -inf and piU_x.l(i) < inf)) = 0;
piU_y.l(i)$(NOT (piU_y.l(i) > -inf and piU_y.l(i) < inf)) = 0;

* ============================================
* Equations
* ============================================

* Stationarity: One equation per primal variable (except objvar)
* Complementarity: Equations for inequalities and bounds
* Equality constraints: Original equality constraints

Equations
    stat_r
    stat_x(i)
    stat_y(i)
    comp_circumscribe(i)
    comp_nooverlap(i,j)
    comp_lo_r
    comp_lo_x(i)
    comp_lo_y(i)
    comp_up_r
    comp_up_x(i)
    comp_up_y(i)
;

* ============================================
* Equation Definitions
* ============================================

$onMultiR
* Stationarity equations
stat_r.. -1 + sum(i, ((-1) * (2 * (1 - r) * (-1))) * lam_circumscribe(i)) + sum((i,j)$(ij(i,j)), 4 * 2 * r * lam_nooverlap(i,j)) - piL_r + piU_r =E= 0;
stat_x(i).. 2 * x(i) * lam_circumscribe(i) + sum(j, (((-1) * (2 * (x(i) - x(j)))) * lam_nooverlap(i,j))$(ij(i,j))) + sum(j, (((-1) * (2 * (x(j) - x(i)) * (-1))) * lam_nooverlap(j,i))$(ij(j,i) and (not sameas(j, i)))) - piL_x(i) + piU_x(i) =E= 0;
stat_y(i).. 2 * y(i) * lam_circumscribe(i) + sum(j, (((-1) * (2 * (y(i) - y(j)))) * lam_nooverlap(i,j))$(ij(i,j))) + sum(j, (((-1) * (2 * (y(j) - y(i)) * (-1))) * lam_nooverlap(j,i))$(ij(j,i) and (not sameas(j, i)))) - piL_y(i) + piU_y(i) =E= 0;

* Inequality complementarity equations
comp_circumscribe(i).. sqr(1 - r) - (sqr(x(i)) + sqr(y(i))) =G= 0;
comp_nooverlap(i,j)$(ij(i,j)).. sqr(x(i) - x(j)) + sqr(y(i) - y(j)) - 4 * sqr(r) =G= 0;

* Lower bound complementarity equations
comp_lo_r.. r - 0.05 =G= 0;
comp_lo_x(i).. x(i) + 1 =G= 0;
comp_lo_y(i).. y(i) + 1 =G= 0;

* Upper bound complementarity equations
comp_up_r.. 0.4 - r =G= 0;
comp_up_x(i).. 1 - x(i) =G= 0;
comp_up_y(i).. 1 - y(i) =G= 0;

$offMulti

* ============================================
* Fix inactive variable instances
* ============================================

* Variables whose paired MCP equation is conditioned must be
* fixed for excluded instances to satisfy MCP matching.

lam_nooverlap.fx(i,j)$(not (ij(i,j))) = 0;

* ============================================
* Model MCP Declaration
* ============================================

* Each line pairs an equation with a variable:
*   equation.variable
*
* This defines the complementarity problem:
*   equation ⊥ variable
*
* Meaning: equation = 0 if variable > 0
*          equation ≥ 0 if variable = 0

Model mcp_model /
    stat_r.r,
    stat_x.x,
    stat_y.y,
    comp_circumscribe.lam_circumscribe,
    comp_nooverlap.lam_nooverlap,
    comp_lo_r.piL_r,
    comp_lo_x.piL_x,
    comp_lo_y.piL_y,
    comp_up_r.piU_r,
    comp_up_x.piU_x,
    comp_up_y.piU_y
/;

* ============================================
* Solve Statement
* ============================================

Solve mcp_model using MCP;

Scalar nlp2mcp_obj_val;
nlp2mcp_obj_val = r.l;
Display nlp2mcp_obj_val;