$onText
Generated by nlp2mcp

This file contains the KKT (Karush-Kuhn-Tucker) conditions
for the original NLP model, transformed into MCP format.

KKT System Components:
  - Stationarity: ∇f + J^T λ + J^T ν - π^L + π^U = 0
  - Complementarity: g(x) ⊥ λ, h(x) = 0, bounds ⊥ π
  - Dual feasibility: λ, π^L, π^U ≥ 0
  - Primal feasibility: g(x) ≤ 0, h(x) = 0, lo ≤ x ≤ up
$offText

* ============================================
* Original Model Declarations
* ============================================

Sets
    i /'1', '2', '3'/
;

Alias(i, j);

Parameters
    a0(i,j) /'1'.'1' 0.12, '1'.'2' 0.1, '1'.'3' 0.049, '2'.'1' 0.21, '2'.'2' 0.247, '2'.'3' 0.265, '3'.'1' 0.026, '3'.'2' 0.249, '3'.'3' 0.145/
    z1(i,j) /'1'.'1' 98, '1'.'2' 72, '1'.'3' 75, '2'.'1' 65, '2'.'2' 8, '2'.'3' 63, '3'.'1' 88, '3'.'2' 27, '3'.'3' 44/
    x(j) /'1' 421, '2' 284, '3' 283/
    u(i)
    v(j)
    a1(i,j)
    r(i) /'1' 1, '2' 1, '3' 1/
    s(j) /'1' 1, '2' 1, '3' 1/
    report(*,i,j)
    zbar(i,j)
;

Scalars
    oldr /0/
    olds /0/
    maxdelta /1/
;

u(i) = sum(j, z1(i,j));
v(j) = sum(i, z1(i,j));

* ============================================
* Variables (Primal + Multipliers)
* ============================================

* Primal variables: Original decision variables from the NLP
* Multipliers:
*   ν (nu_*): Free multipliers for equality constraints
*   λ (lam_*): Positive multipliers for inequality constraints
*   π^L (piL_*): Positive multipliers for lower bounds
*   π^U (piU_*): Positive multipliers for upper bounds

Variables
    obj
    nu_colbal(i)
;

Positive Variables
    a(i,j)
    piL_a(i,j)
;

* ============================================
* Variable Initialization
* ============================================

* Initialize variables to avoid division by zero during model generation.
* Variables appearing in denominators (from log, 1/x derivatives) need
* non-zero initial values.
* POSITIVE variables with explicit .l values are
* clamped to min(max(value, 1e-6), upper_bound).

a.l('1','1') = 1e-05;
a.l('1','2') = 1e-05;
a.l('1','3') = 1e-05;
a.l('2','1') = 1e-05;
a.l('2','2') = 1e-05;
a.l('2','3') = 1e-05;
a.l('3','1') = 1e-05;
a.l('3','2') = 1e-05;
a.l('3','3') = 1e-05;
a.l(i,j) = min(max(a.l(i,j), 1e-6), a.up(i,j));

* ============================================
* Equations
* ============================================

* Stationarity: One equation per primal variable (except objvar)
* Complementarity: Equations for inequalities and bounds
* Equality constraints: Original equality constraints

Equations
    stat_a(i,j)
    comp_lo_a(i,j)
    colbal(j)
    defrsd
;

* ============================================
* Equation Definitions
* ============================================

* Stationarity equations
stat_a(i,j).. a0(i,j) * 2 * (a(i,j) + a0(i,j)) / sqr(a0(i,j)) + x(i) * nu_colbal(i) - piL_a(i,j) =E= 0;

* Lower bound complementarity equations
comp_lo_a(i,j).. a(i,j) - 1e-05 =G= 0;

* Original equality equations
colbal(j).. sum(i, a(i,j) * x(j)) =E= v(j);
defrsd.. obj =E= sum((i,j), sqr(a(i,j) + a0(i,j)) / a0(i,j));


* ============================================
* Model MCP Declaration
* ============================================

* Each line pairs an equation with a variable:
*   equation.variable
*
* This defines the complementarity problem:
*   equation ⊥ variable
*
* Meaning: equation = 0 if variable > 0
*          equation ≥ 0 if variable = 0

Model mcp_model /
    stat_a.a,
    colbal.nu_colbal,
    defrsd.obj,
    comp_lo_a.piL_a
/;

* ============================================
* Solve Statement
* ============================================

Solve mcp_model using MCP;

Scalar nlp2mcp_obj_val;
nlp2mcp_obj_val = obj.l;
Display nlp2mcp_obj_val;