$onText
Generated by nlp2mcp

This file contains the KKT (Karush-Kuhn-Tucker) conditions
for the original NLP model, transformed into MCP format.

KKT System Components:
  - Stationarity: ∇f + J^T λ + J^T ν - π^L + π^U = 0
  - Complementarity: g(x) ⊥ λ, h(x) = 0, bounds ⊥ π
  - Dual feasibility: λ, π^L, π^U ≥ 0
  - Primal feasibility: g(x) ≤ 0, h(x) = 0, lo ≤ x ≤ up
$offText

* ============================================
* Original Model Declarations
* ============================================

Sets
    i /'1', '2', '3', '4', '5', '6', '7'/
    j /'1', '2', '3', '4'/
;

Alias(j, k);

Parameters
    b(i) /'1' 1, '2' 1, '3' 1, '4' 1, '5' 1, '6' 1, '7' 1/
    c(j) /'1' -1, '2' -1, '3' -1, '4' -1/
    A(i,j)
    results(*,*)
    P(i,j,k) /'1'.'1'.'1' 0.01, '1'.'2'.'2' 0.01, '1'.'3'.'3' 0.01, '1'.'4'.'4' 0.01, '2'.'1'.'1' 0.01, '2'.'2'.'2' 0.01, '2'.'3'.'3' 0.01, '2'.'4'.'4' 0.01, '3'.'1'.'1' 0.01, '3'.'2'.'2' 0.01, '3'.'3'.'3' 0.01, '3'.'4'.'4' 0.01, '4'.'1'.'1' 0.01, '4'.'2'.'2' 0.01, '4'.'3'.'3' 0.01, '4'.'4'.'4' 0.01, '5'.'1'.'1' 0.01, '5'.'2'.'2' 0.01, '5'.'3'.'3' 0.01, '5'.'4'.'4' 0.01, '6'.'1'.'1' 0.01, '6'.'2'.'2' 0.01, '6'.'3'.'3' 0.01, '6'.'4'.'4' 0.01, '7'.'1'.'1' 0.01, '7'.'2'.'2' 0.01, '7'.'3'.'3' 0.01, '7'.'4'.'4' 0.01/
;

Scalars
    mu /0.01/
;

* Fix random seed for deterministic MCP evaluation
execseed = 12345;

A(i,j) = uniform(0, 1);

execError = 0;

* ============================================
* Variables (Primal + Multipliers)
* ============================================

* Primal variables: Original decision variables from the NLP
* Multipliers:
*   ν (nu_*): Free multipliers for equality constraints
*   λ (lam_*): Positive multipliers for inequality constraints
*   π^L (piL_*): Positive multipliers for lower bounds
*   π^U (piU_*): Positive multipliers for upper bounds

Variables
    obj
    x(j)
    y(i)
    v(i,k)
    nu_defobj(i)
    nu_defrhs(i)
    nu_defv(i,k)
;

Positive Variables
    lam_socpqcpcons(i)
    piL_y(i)
;

* ============================================
* Equations
* ============================================

* Stationarity: One equation per primal variable (except objvar)
* Complementarity: Equations for inequalities and bounds
* Equality constraints: Original equality constraints

Equations
    stat_obj
    stat_v(i,k)
    stat_x(j)
    stat_y(i)
    comp_socpqcpcons(i)
    comp_lo_y(i)
    defobj(i)
    defrhs(i)
    defv(i,k)
;

* ============================================
* Equation Definitions
* ============================================

* Stationarity equations
stat_obj.. 1 + sum(i, nu_defobj(i)) =E= 0;
stat_v(i,k).. nu_defv(i,k) + 2 * v(i,k) * lam_socpqcpcons(i) =E= 0;
stat_x(j).. sum(i, ((-1) * c(j)) * nu_defobj(i)) + sum(i, A(i,j) * nu_defrhs(i)) + sum((i,k), ((-1) * P(i,j,k)) * nu_defv(i,k)) =E= 0;
stat_y(i).. nu_defrhs(i) + ((-1) * (2 * y(i))) * lam_socpqcpcons(i) - piL_y(i) =E= 0;

* Inequality complementarity equations
comp_socpqcpcons(i).. sqr(y(i)) - sum(k, sqr(v(i,k))) =G= 0;

* Lower bound complementarity equations
comp_lo_y(i).. y(i) - 0 =G= 0;

* Original equality equations
defobj(i).. obj =E= sum(j, c(j) * x(j));
defrhs(i).. y(i) =E= b(i) - sum(j, A(i,j) * x(j));
defv(i,k).. v(i,k) =E= sum(j, P(i,j,k) * x(j));


* ============================================
* Model MCP Declaration
* ============================================

* Each line pairs an equation with a variable:
*   equation.variable
*
* This defines the complementarity problem:
*   equation ⊥ variable
*
* Meaning: equation = 0 if variable > 0
*          equation ≥ 0 if variable = 0

Model mcp_model /
    stat_obj.obj,
    stat_v.v,
    stat_x.x,
    stat_y.y,
    comp_socpqcpcons.lam_socpqcpcons,
    defobj.nu_defobj,
    defrhs.nu_defrhs,
    defv.nu_defv,
    comp_lo_y.piL_y
/;

* ============================================
* Solve Statement
* ============================================

Solve mcp_model using MCP;

Scalar nlp2mcp_obj_val;
nlp2mcp_obj_val = obj.l;
Display nlp2mcp_obj_val;