$onText
Generated by nlp2mcp

This file contains the KKT (Karush-Kuhn-Tucker) conditions
for the original NLP model, transformed into MCP format.

KKT System Components:
  - Stationarity: ∇f + J^T λ + J^T ν - π^L + π^U = 0
  - Complementarity: g(x) ⊥ λ, h(x) = 0, bounds ⊥ π
  - Dual feasibility: λ, π^L, π^U ≥ 0
  - Primal feasibility: g(x) ≤ 0, h(x) = 0, lo ≤ x ≤ up
$offText

* ============================================
* Original Model Declarations
* ============================================

* ============================================
* Variables (Primal + Multipliers)
* ============================================

* Primal variables: Original decision variables from the NLP
* Multipliers:
*   ν (nu_*): Free multipliers for equality constraints
*   λ (lam_*): Positive multipliers for inequality constraints
*   π^L (piL_*): Positive multipliers for lower bounds
*   π^U (piU_*): Positive multipliers for upper bounds

Variables
    x
    y
    z
    obj
    aux_min_min_constraint_0
    nu_min_constraint
;

Positive Variables
    lambda_min_min_constraint_0_arg0
    lambda_min_min_constraint_0_arg1
    lam_comp_min_min_constraint_0_arg0
    lam_comp_min_min_constraint_0_arg1
    piL_x
    piL_y
    piL_lambda_min_min_constraint_0_arg0
    piL_lambda_min_min_constraint_0_arg1
;

* ============================================
* Equations
* ============================================

* Stationarity: One equation per primal variable (except objvar)
* Complementarity: Equations for inequalities and bounds
* Equality constraints: Original equality constraints

Equations
    stat_aux_min_min_constraint_0
    stat_lambda_min_min_constraint_0_arg0
    stat_lambda_min_min_constraint_0_arg1
    stat_x
    stat_y
    stat_z
    comp_comp_min_min_constraint_0_arg0
    comp_comp_min_min_constraint_0_arg1
    comp_lo_lambda_min_min_constraint_0_arg0
    comp_lo_lambda_min_min_constraint_0_arg1
    comp_lo_x
    comp_lo_y
    min_constraint
    objective
;

* ============================================
* Equation Definitions
* ============================================

* Stationarity equations
stat_aux_min_min_constraint_0.. 0 + (-1) * nu_min_constraint + 1 * lam_comp_min_min_constraint_0_arg0 + 1 * lam_comp_min_min_constraint_0_arg1 =E= 0;
stat_lambda_min_min_constraint_0_arg0.. 0 + 0 * nu_min_constraint + 0 * lam_comp_min_min_constraint_0_arg0 + 0 * lam_comp_min_min_constraint_0_arg1 - piL_lambda_min_min_constraint_0_arg0 =E= 0;
stat_lambda_min_min_constraint_0_arg1.. 0 + 0 * nu_min_constraint + 0 * lam_comp_min_min_constraint_0_arg0 + 0 * lam_comp_min_min_constraint_0_arg1 - piL_lambda_min_min_constraint_0_arg1 =E= 0;
stat_x.. 0 + 0 * nu_min_constraint + (-1) * lam_comp_min_min_constraint_0_arg0 + 0 * lam_comp_min_min_constraint_0_arg1 - piL_x =E= 0;
stat_y.. 0 + 0 * nu_min_constraint + 0 * lam_comp_min_min_constraint_0_arg0 + (-1) * lam_comp_min_min_constraint_0_arg1 - piL_y =E= 0;
stat_z.. 1 + 1 * nu_min_constraint + 0 * lam_comp_min_min_constraint_0_arg0 + 0 * lam_comp_min_min_constraint_0_arg1 =E= 0;

* Inequality complementarity equations
comp_comp_min_min_constraint_0_arg0.. -(x - aux_min_min_constraint_0) =G= 0;
comp_comp_min_min_constraint_0_arg1.. -(y - aux_min_min_constraint_0) =G= 0;

* Lower bound complementarity equations
comp_lo_lambda_min_min_constraint_0_arg0.. lambda_min_min_constraint_0_arg0 - 0 =G= 0;
comp_lo_lambda_min_min_constraint_0_arg1.. lambda_min_min_constraint_0_arg1 - 0 =G= 0;
comp_lo_x.. x - 1 =G= 0;
comp_lo_y.. y - 2 =G= 0;

* Original equality equations
objective.. obj =E= z;
min_constraint.. z =E= aux_min_min_constraint_0;


* ============================================
* Model MCP Declaration
* ============================================

* Each line pairs an equation with a variable:
*   equation.variable
*
* This defines the complementarity problem:
*   equation ⊥ variable
*
* Meaning: equation = 0 if variable > 0
*          equation ≥ 0 if variable = 0

Model mcp_model /
    stat_aux_min_min_constraint_0.aux_min_min_constraint_0,
    stat_lambda_min_min_constraint_0_arg0.lambda_min_min_constraint_0_arg0,
    stat_lambda_min_min_constraint_0_arg1.lambda_min_min_constraint_0_arg1,
    stat_x.x,
    stat_y.y,
    stat_z.z,
    comp_comp_min_min_constraint_0_arg0.lam_comp_min_min_constraint_0_arg0,
    comp_comp_min_min_constraint_0_arg1.lam_comp_min_min_constraint_0_arg1,
    min_constraint.nu_min_constraint,
    objective.obj,
    comp_lo_lambda_min_min_constraint_0_arg0.piL_lambda_min_min_constraint_0_arg0,
    comp_lo_lambda_min_min_constraint_0_arg1.piL_lambda_min_min_constraint_0_arg1,
    comp_lo_x.piL_x,
    comp_lo_y.piL_y
/;

* ============================================
* Solve Statement
* ============================================

Solve mcp_model using MCP;