$onText
Generated by nlp2mcp

This file contains the KKT (Karush-Kuhn-Tucker) conditions
for the original NLP model, transformed into MCP format.

KKT System Components:
  - Stationarity: ∇f + J^T λ + J^T ν - π^L + π^U = 0
  - Complementarity: g(x) ⊥ λ, h(x) = 0, bounds ⊥ π
  - Dual feasibility: λ, π^L, π^U ≥ 0
  - Primal feasibility: g(x) ≤ 0, h(x) = 0, lo ≤ x ≤ up
$offText

* ============================================
* Original Model Declarations
* ============================================

Sets
    i /i1, i2, i3/
;

Parameters
    a(i) /i1 1.0, i2 2.0, i3 3.0/
;

* ============================================
* Variables (Primal + Multipliers)
* ============================================

* Primal variables: Original decision variables from the NLP
* Multipliers:
*   ν (nu_*): Free multipliers for equality constraints
*   λ (lam_*): Positive multipliers for inequality constraints
*   π^L (piL_*): Positive multipliers for lower bounds
*   π^U (piU_*): Positive multipliers for upper bounds

Variables
    x(i)
    obj
    nu_objective
;

Positive Variables
    lam_balance(i)
;

* ============================================
* Equations
* ============================================

* Stationarity: One equation per primal variable (except objvar)
* Complementarity: Equations for inequalities and bounds
* Equality constraints: Original equality constraints

Equations
    stat_x_i1
    stat_x_i2
    stat_x_i3
    comp_balance
    objective
;

* ============================================
* Equation Definitions
* ============================================

* Stationarity equations
stat_x_i1(i1).. x(i1) * 0 + a(i1) * 1 + (1 - 0) * lam_balance(i1) + (0 - 0) * lam_balance(i2) + (0 - 0) * lam_balance(i3) =E= 0;
stat_x_i2(i2).. x(i2) * 0 + a(i2) * 1 + (0 - 0) * lam_balance(i1) + (1 - 0) * lam_balance(i2) + (0 - 0) * lam_balance(i3) =E= 0;
stat_x_i3(i3).. x(i3) * 0 + a(i3) * 1 + (0 - 0) * lam_balance(i1) + (0 - 0) * lam_balance(i2) + (1 - 0) * lam_balance(i3) =E= 0;

* Inequality complementarity equations
comp_balance(i).. -x(i) =G= 0;

* Original equality equations
objective.. obj =E= sum(i, a(i) * x(i));


* ============================================
* Model MCP Declaration
* ============================================

* Each line pairs an equation with a variable:
*   equation.variable
*
* This defines the complementarity problem:
*   equation ⊥ variable
*
* Meaning: equation = 0 if variable > 0
*          equation ≥ 0 if variable = 0

Model mcp_model /
    * Stationarity conditions
    stat_x_i1.x(i1)
    stat_x_i2.x(i2)
    stat_x_i3.x(i3)

    * Inequality complementarities
    comp_balance.lam_balance(i)

    * Equality constraints
    objective.obj
/;

* ============================================
* Solve Statement
* ============================================

Solve mcp_model using MCP;