name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black mypy
        pip install -r requirements.txt

    - name: Run Ruff (fast linter)
      run: |
        ruff check src/ tests/
      continue-on-error: true

    - name: Check code formatting with Black
      run: |
        black --check src/ tests/
      continue-on-error: true

    - name: Run type checking with mypy
      run: |
        mypy src/ --ignore-missing-imports
      continue-on-error: true
